### ISSUE TITLE
Qubes support

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#17]
Is Qubes (Qubes ProxyVMs) officially supported? Tested by you?

If you/no, let's please add this to corridor's readme.

There are some things in Qubes that may interfere with firewall rules:

* qubes-iptables
* qubes-firewall
* [/usr/lib/qubes/qubes-setup-dnat-to-ns](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/qubes-setup-dnat-to-ns) ([reference](https://phabricator.whonix.org/T502))

Related:

* https://github.com/rustybird/corridor/issues/10
* https://github.com/QubesOS/qubes-issues/issues/2108
* https://www.whonix.org/wiki/Corridor

**Comment by rustybird** [comment]
> Is Qubes (Qubes ProxyVMs) officially supported? Tested by you?

No, not at all. That's why it's not in master yet

**Comment by rustybird** [comment]
I've pushed some more orderings to the qubes branch and tested them a little (on Fedora 23). ProxyVM startup seems to work correctly.

Unfortunately, as soon as you connect a client VM to the corridor VM, the filter rules get clobbered. Pretty sure that's https://github.com/QubesOS/qubes-issues/issues/1555

**Comment by adrelanos** [comment]
Why not deactivate all Qubes firewall stuff and only let corridor work?

**Comment by rustybird** [comment]
> Why not deactivate all Qubes firewall stuff and only let corridor work?

Yes... :)
