### ISSUE TITLE
Qubes mkdir -p "$RELAYS_STATE" missing

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#20]
* https://github.com/rustybird/corridor/blob/master/qubes/corridor.d/31-state-qubes.conf
* `Makefile_orig`:  `install -d $(DESTDIR)$(SBIN) $(DESTDIR)$(MAN)/man8 $(DESTDIR)/etc/corridor.d $(DESTDIR)/var/lib/corridor`
* https://github.com/rustybird/corridor/blob/master/sbin/corridor-data

Unless I am missing something, for Qubes there is some. `mkdir -p "$RELAYS_STATE"` required. For `/var/lib/corridor` non-Qubes case you handle it in the makefile but for the Qubes case this is currently not handled. I guess folder existence should be checked/created in `corridor-data`.

**Comment by rustybird** [comment]
corridor_relays is the filename, it is created directly in /rw (which will already exist)
