### ISSUE TITLE
Qubes: systemd corridor-data.service should wait for /rw

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#21]
* https://github.com/rustybird/corridor/blob/master/qubes/corridor.d/31-state-qubes.conf
* https://github.com/rustybird/corridor/blob/master/systemd/corridor-data.service.in
* https://github.com/rustybird/corridor/blob/master/qubes/systemd/corridor-data.service.d/qubes.conf

-----

* https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/qubes-sysinit.service
* https://github.com/marmarek/qubes-core-agent-linux/blob/master/vm-systemd/qubes-mount-dirs.service

-----

`corridor-data.service` should probably run after `qubes-mount-dirs.service` or even after `qubes-sysinit.service`? Otherwise `/rw` may not be available at that time.

**Comment by rustybird** [comment]
Thanks! I had somehow assumed that qubes-mount-dirs.service is part of sysinit.target.

**Comment by adrelanos** [comment]
@rustybird 
> Thanks! I had somehow assumed that qubes-mount-dirs.service is part of sysinit.target.

Which is not an unreasonable assumption at all. Perhaps that should be considered a native Qubes bug? Perhaps Qubes should make sure the mount dirs stuff is done in time?
