### ISSUE TITLE
Qubes: also process /rw/corridor.d configuration folder

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#22]
https://github.com/rustybird/corridor/blob/master/sbin/corridor-load-config

Please also `source` configuration files in `/rw/corridor.d` folder. It should have a higher priority than `/etc/corridor.d`. I.e. `source` `/rw/corridor.d` frist followed by `/rw/corridor.d`.

**Comment by rustybird** [comment]
Maybe /usr/local/etc/corridor.d, because it is not Qubes specific but happens to be in /rw on Qubes.

**Comment by adrelanos** [comment]
Yes, I guess that would serve the same purpose.
