### ISSUE TITLE
clarify compatibility with ufw

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#26]
We are [wondering](https://phabricator.whonix.org/T524#9516), is corridor (as a host firewall #3) compatible with ufw? Has this been tested? Is that discouraged?

Please clarify. Then documentation will perhaps recommend to uninstall ufw first. (And I'd add a `Conflicts:` for Debian packaging. (#10))

**Comment by rustybird** [comment]
I've never tried ufw.

**Comment by adrelanos** [comment]
I wonder if combination with ufw should be discouraged then?

I think unless one is intimate how ufw works, with its instructions on how it can be combined with other iptables rules, ufw is a recipe for disaster. It might either break what ufw is doing, or what corridor is doing, or even both.

ufw documentation on combining ufw with other iptables rules at https://wiki.ubuntu.com/UncomplicatedFirewall#Advanced_Functionality tells me, corridor and ufw cannot be easily combined.

//cc @HulaHoopWhonix
