### ISSUE TITLE
missing make all target

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#35]
`make all` is a default target. [1]

For standard compliance, can we add a `make all` target please?

(Background: This would make some thing in genmkfile easier. [Adding compilation feature.] However, if this is not a standard thing, then I'll find another solution.)

[1] https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html

**Comment by rustybird** [comment]
Happy new year! So `all` would be a non-default target depending on `man/corridor.8` and `systemd-units`?

**Comment by adrelanos** [comment]
Happy new year!

By convention, 'all' is both, default and first target. What it would
depend upon, dunno. Perhaps even nothing and just echo "not required,
done" or so?

**Comment by rustybird** [comment]
Would `all` work for your genmkfile use case if it was the second target and depended on `man/corridor.8` and `systemd-units`?

(Making `all` not build everything sounds a little strange. And I'd prefer the first target to be appropriate for every user, including those without systemd.)

**Comment by adrelanos** [comment]
Rusty Bird:
> Would `all` work for your genmkfile use case if it was the second
> target and depended on `man/corridor.8` and `systemd-units`?

I guess so. Important is only that 'make all' does anything but exit
non-zero. Since the other steps are idempotent, it should not really matter.

Somewhat related, on make file conventions.

- https://lists.debian.org/debian-mentors/2017/01/msg00058.html

- https://lists.debian.org/debian-mentors/2017/01/msg00059.html
