### ISSUE TITLE
/etc/torrc.d/ vs bridges grep?

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#42]
BRIDGES=`grep -Ei '^[[:space:]]*Bridge[[:space:]]' /usr/local/etc/torrc.d/*`

Doesn't work anymore.

Know any line that works with /etc/torrc.d/?

**Comment by rustybird** [comment]
Looks like the whole approach of parsing the tor configuration pretty much broken. With %include directives, configuration files could reasonably be anywhere on the file system.

I'm leaning towards just deleting `20-bridges-auto.conf` and replacing it with a `20-bridges.conf.EXAMPLE` file (which would show the syntax of the `BRIDGES` variable).

**Comment by adrelanos** [comment]
Would

```
BRIDGES="\
Bridge 1.2.3.4:443
Bridge 2.3.4.5:443
"
```

Work?

**Comment by adrelanos** [comment]
Using backslash here to simplify the syntax for users.

https://www.whonix.org/wiki/Corridor#Optional:_BridgeFirewall_corridor_Configuration
