### ISSUE TITLE
create a signed git tag, create a release

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#9]
Whonix corridor instructions WIP:
https://www.whonix.org/wiki/Corridor

It would help if there was a release, a signed git tag that users could be pointed at.

**Comment by rustybird** [comment]
Why not `git verify-commit <commit>`?

Master is supposed to stay usable and permanent, with experimental stuff going into other branches, e.g. I just uploaded https://github.com/rustybird/corridor/tree/qubes/qubes

**Comment by rustybird** [comment]
> Whonix corridor instructions WIP:
> https://www.whonix.org/wiki/Corridor

Nice, thanks! By the way, I'm working on automatically setting up a logging DNS server, similar to [how it's done in orplug](https://github.com/rustybird/orplug/blob/master/orplug/bin/orplug-start#L96-L98).

**Comment by adrelanos** [comment]
> Master is supposed to stay usable and permanent, with experimental stuff going into other branches, e.g. I just uploaded https://github.com/rustybird/corridor/tree/qubes/qubes
> 

Cool!

Which version number would we give the package if it gets uploaded to
the Whonix or even Debian repository?

Perhaps we just count the number of git commits and use that as version
number?

**Comment by rustybird** [comment]
I think the ISO 8601 timestamp (without separators) of the last commit is often used, e.g. [corridor-20160704102229](https://github.com/rustybird/corridor/commit/75244c17a9ed0569faa00f1181644d847a2840ac.patch)

**Comment by adrelanos** [comment]
Do you know the git command to create this format?

**Comment by rustybird** [comment]
Maybe something like

    git show --no-patch --pretty=format:%ai <commit> |
    tr -dc 0-9 |
    cut -b 1-14

**Comment by adrelanos** [comment]
I find these version numbers difficult to read, but it's your call.
